@OptionalSecretService_HostAddress = https://localhost:7014

GET {{OptionalSecretService_HostAddress}}/secret/A
Accept: application/json

###
GET {{OptionalSecretService_HostAddress}}/secret/B
Accept: application/json

###
GET {{OptionalSecretService_HostAddress}}/secret/C
Accept: application/json

###
GET {{OptionalSecretService_HostAddress}}/secret/D
Accept: application/json

###
